### ISSUE TITLE
ClientStreamAbortedException logged at SEVERE level, should be at lower level

### ISSUE THREAD

**Issue by tixvieira** [geosolutions-it/imageio-ext#181]
Geoserver 2.14 is using imageio-ext 1.1.25.

A bug is already solved for the logger level of a "ClientStreamAbortedException":
https://osgeo-org.atlassian.net/browse/GEOS-8958

But I notice that it appears sometimes on the logs again.
It comes from PNGWriter class:
`11-Dec-2018 16:36:52.213 SEVERE [http-nio-3000-exec-1] it.geosolutions.imageio.plugins.png.PNGWriter.writePNG Failed to encode the PNG
 ar.com.hjg.pngj.PngjOutputException: org.geoserver.ows.ClientStreamAbortedException
        at ar.com.hjg.pngj.PngHelperInternal.writeBytes(PngHelperInternal.java:196)
        at ar.com.hjg.pngj.chunks.ChunkRaw.writeChunk(ChunkRaw.java:97)
        at ar.com.hjg.pngj.PngIDatChunkOutputStream.flushBuffer(PngIDatChunkOutputStream.java:28)
        at ar.com.hjg.pngj.ProgressiveOutputStream.checkFlushBuffer(ProgressiveOutputStream.java:65)
        at ar.com.hjg.pngj.ProgressiveOutputStream.flush(ProgressiveOutputStream.java:28)
        at ar.com.hjg.pngj.PngWriter.end(PngWriter.java:400)
        at it.geosolutions.imageio.plugins.png.PNGWriter.writePNG(PNGWriter.java:110)
        at it.geosolutions.imageio.plugins.png.PNGWriter.writePNG(PNGWriter.java:48)
        at org.geoserver.wms.map.png.PNGJWriter.writePNG(PNGJWriter.java:51)
        at org.geoserver.wms.map.PNGMapResponse.formatImageOutputStream(PNGMapResponse.java:104)
        at org.geoserver.wms.map.RenderedImageMapResponse.write(RenderedImageMapResponse.java:111)
        at org.geoserver.ows.Dispatcher.response(Dispatcher.java:1032)
        at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:268)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)`

At this class exists a logger at level SEVERE:
`LOGGER.log(Level.SEVERE, "Failed to encode the PNG", e);`

I don't know much about this project, so i don't know if i can remove this logger from this line, or just put it to level DEBUG ou FINE.

Can you give me your suggestion?

Thanks

**Comment by aaime** [comment]
I have no objections to this change, please go on :-)

**Comment by tixvieira** [comment]
Can you do the merge of this PR?
Do you have a roadmap of releases or you can do it after this merge?
I want to create the PR on Geoserver :)
https://osgeo-org.atlassian.net/browse/GEOS-9057

**Comment by tixvieira** [comment]
Any news on this PR?
